# Generated by Django 2.2.5 on 2019-11-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=128, verbose_name='物品名称')),
                ('gnumber', models.IntegerField(verbose_name='物品数量')),
                ('gintime', models.DateTimeField(null=True, verbose_name='添加时间')),
                ('guser', models.CharField(max_length=32, verbose_name='操作用户')),
                ('gother', models.CharField(max_length=32, verbose_name='备注')),
            ],
        ),
    ]
